filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: nginx
repositories:
repositories:
- name: local
  url: http://192.168.122.90/chartrepo/library
releases:
- chart: ingress-nginx/ingress-nginx
  version: 3.12.0
  name: nginx-ingress
  values:
  - ../../versionStream/charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
  - ../../versionStream/charts/ingress-nginx/ingress-nginx/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
