filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: tekton-pipelines
repositories:
- name: local
  url: http://192.168.122.90/chartrepo/library
releases:
- chart: local/tekton-pipeline
  version: 0.22.0
  name: tekton-pipeline
  values:
  - ../../versionStream/charts/cdf/tekton-pipeline/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
